server:
  port: 80
  servlet-path: /

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/dbtest?useUnicode=true&amp;characterEncoding=utf-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

service:
  starter:
    enable: true
    prefix: aaaaaaaaaaaaa
    suffix: cccccccccccccc